image: comp1531/automarking:latest

stages:
  - checks

before_script:
  - npm install

tests:
  stage: checks
  script:
    - SERVER_LOG=$(mktemp)
    - time npm run coverage >& $SERVER_LOG &
    - timeout 10s grep -q "⚡️ Server started on port" <(tail -f $SERVER_LOG) || (cat $SERVER_LOG && exit 1)
    - timeout -s SIGINT 180s npm run test || (cat $SERVER_LOG && exit 1)
    - kill -SIGINT %1
    - sleep 2
    - cat $SERVER_LOG
  coverage: '/All files\s*\|\s*(\d+(?:\.\d+)?)/'
  artifacts:
    untracked: true
    paths:
      - coverage/
    expose_as: Coverage Report
    expire_in: 3 days

typecheck:
  stage: checks
  script:
    - npm run tsc

linting:
  stage: checks
  script:
    - npm run lint
