image: comp1531/automarking:latest

stages:
  - checks

before_script:
  - npm install

tests:
  stage: checks
  script:
    - SERVER_LOG=$(mktemp)
    - TEST_LOG=$(mktemp)
    - npm run coverage >& $SERVER_LOG &
    - timeout 10s grep -q "⚡️ Server started on port" <(tail -f $SERVER_LOG) || (cat $SERVER_LOG && exit 1)
    - time npm run test >& $TEST_LOG|| (cat $SERVER_LOG && exit 1)
    - kill -SIGINT %1 >> "${SERVER_LOG}" 2>&1
    - sleep 2
    - echo "Server Log:"
    - cat $SERVER_LOG
    - echo "Test Log:"
    - cat $TEST_LOG
    - echo "Coverage Log:"
    - ls -la coverage/ || echo "coverage/ directory not found"
    - cat $COVERAGE_LOG
  coverage: '/All files\s*\|\s*(\d+(?:\.\d+)?)/'
  artifacts:
    paths:
      - coverage/
    expose_as: Coverage Report
    expire_in: 3 days

typecheck:
  stage: checks
  script:
    - npm run tsc

linting:
  stage: checks
  script:
    - npm run lint
