image: comp1531/automarking:latest

stages:
  - checks

before_script:
  - npm install

tests:
  stage: checks
  except:
    - iteration2/vic/dryRun
  script:
    - SERVER_LOG=$(mktemp)
    - TEST_WITH_COVERAGE_LOG=$(mktemp)
<<<<<<< HEAD
    - npm run start >& $SERVER_LOG &
    # - timeout 10s grep -q "⚡️ Server started on port" <(tail -f $SERVER_LOG) || (cat $SERVER_LOG && exit 1)
    # - timeout -s SIGINT 180s
    - time npm run coverage_pipeline || (cat $SERVER_LOG && cat $TEST_WITH_COVERAGE_LOG && exit 1)
=======
    - npm run coverage >& $SERVER_LOG &
    - timeout 10s grep -q "⚡️ Server started on port" <(tail -f $SERVER_LOG) || (cat $SERVER_LOG && exit 1)
    - timeout -s SIGINT 180s time npm t || (cat $SERVER_LOG && cat $TEST_WITH_COVERAGE_LOG && exit 1)
>>>>>>> 511cb2f (complete life cycle: token now in header)
    - kill -SIGINT %1
    # - cat $SERVER_LOG
    - npm run coverage_report
    - cat coverage/lcov.info || echo "lcov.info not found"
  coverage: '/All files\s*\|\s*(\d+(?:\.\d+)?)/'
  artifacts:
    paths: 
      - coverage/
    expose_as: 'Coverage Report'
    expire_in: 3 days

typecheck:
  stage: checks
  script:
    - npm run tsc

linting:
  stage: checks
  script:
    - npm run lint
