image: comp1531/automarking:latest

stages:
  - checks

before_script:
  - npm install

tests:
  stage: checks
  except:
    - iteration2/vic/dryRun
  script:
    - SERVER_LOG=$(mktemp)
    - TEST_WITH_COVERAGE_LOG=$(mktemp)
    - npm run start >& $SERVER_LOG &
    # - timeout 10s grep -q "⚡️ Server started on port" <(tail -f $SERVER_LOG) || (cat $SERVER_LOG && exit 1)
    # - timeout -s SIGINT 180s
    - time npm run coverage_pipeline || (cat $SERVER_LOG && cat $TEST_WITH_COVERAGE_LOG && exit 1)
    - kill -SIGINT %1
    # - cat $SERVER_LOG
    - npm run report2
    - cat coverage/lcov.info
    - grep -A 5 "<div class='pad1'>" coverage/lcov-report/index.html || echo "No coverage report found"
  coverage: '/All files\s*\|\s*(\d+(?:\.\d+)?)/'
  artifacts:
    paths: 
      - coverage/
    expose_as: 'Coverage Report'
    expire_in: 3 days

# typecheck:
#   stage: checks
#   script:
#     - npm run tsc

# linting:
#   stage: checks
#   script:
#     - npm run lint
